name: Build

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run ci:test
      # - name: Coverage
      #   run: npm run coverage
      # - uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true
